# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CorrectAnswerWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CorrectAnswer(object):
    def setupUi(self, CorrectAnswer):
        CorrectAnswer.setObjectName("CorrectAnswer")
        CorrectAnswer.resize(471, 148)
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        font.setBold(True)
        font.setWeight(75)
        CorrectAnswer.setFont(font)
        CorrectAnswer.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(CorrectAnswer)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(190, 0, 121, 71))
        font = QtGui.QFont()
        font.setFamily("Caladea")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(0, 90, 131, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(170, 90, 131, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(340, 90, 131, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        CorrectAnswer.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(CorrectAnswer)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 471, 17))
        self.menubar.setObjectName("menubar")
        CorrectAnswer.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(CorrectAnswer)
        self.statusbar.setObjectName("statusbar")
        CorrectAnswer.setStatusBar(self.statusbar)

        self.retranslateUi(CorrectAnswer)
        QtCore.QMetaObject.connectSlotsByName(CorrectAnswer)

    def retranslateUi(self, CorrectAnswer):
        _translate = QtCore.QCoreApplication.translate
        CorrectAnswer.setWindowTitle(_translate("CorrectAnswer", "MainWindow"))
        self.label.setText(_translate("CorrectAnswer", "<html><head/><body><p><span style=\" font-size:22pt; color:#00aa00;\">Верно!</span></p></body></html>"))
        self.pushButton.setText(_translate("CorrectAnswer", "Главное меню"))
        self.pushButton_2.setText(_translate("CorrectAnswer", "Выбор задания"))
        self.pushButton_3.setText(_translate("CorrectAnswer", "Статистика"))
