# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CorrectAnswerWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CorrectAnswer(object):
    def setupUi(self, CorrectAnswer):
        CorrectAnswer.setObjectName("CorrectAnswer")
        CorrectAnswer.resize(471, 148)
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        font.setBold(True)
        font.setWeight(75)
        CorrectAnswer.setFont(font)
        CorrectAnswer.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(CorrectAnswer)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 0, 471, 111))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 1, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.widget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 1, 1, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.widget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 1, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Caladea")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        CorrectAnswer.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(CorrectAnswer)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 471, 17))
        self.menubar.setObjectName("menubar")
        CorrectAnswer.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(CorrectAnswer)
        self.statusbar.setObjectName("statusbar")
        CorrectAnswer.setStatusBar(self.statusbar)

        self.retranslateUi(CorrectAnswer)
        QtCore.QMetaObject.connectSlotsByName(CorrectAnswer)

    def retranslateUi(self, CorrectAnswer):
        _translate = QtCore.QCoreApplication.translate
        CorrectAnswer.setWindowTitle(_translate("CorrectAnswer", "MainWindow"))
        self.pushButton.setText(_translate("CorrectAnswer", "Главное меню"))
        self.pushButton_2.setText(_translate("CorrectAnswer", "Выбор задания"))
        self.pushButton_3.setText(_translate("CorrectAnswer", "Статистика"))
        self.label.setText(_translate("CorrectAnswer", "<html><head/><body><p align=\"center\"><span style=\" font-size:22pt; color:#00aa00;\">Верно!</span></p></body></html>"))
