# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'InCorrectAnswerWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_InCorrectAnswer(object):
    def setupUi(self, InCorrectAnswer):
        InCorrectAnswer.setObjectName("InCorrectAnswer")
        InCorrectAnswer.resize(516, 147)
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        font.setBold(True)
        font.setWeight(75)
        InCorrectAnswer.setFont(font)
        self.centralwidget = QtWidgets.QWidget(InCorrectAnswer)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 0, 511, 111))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Caladea")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 2)
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 1, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.widget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 1, 1, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.widget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 1, 2, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.widget)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout.addWidget(self.pushButton_4, 1, 3, 1, 1)
        InCorrectAnswer.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(InCorrectAnswer)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 516, 17))
        self.menubar.setObjectName("menubar")
        InCorrectAnswer.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(InCorrectAnswer)
        self.statusbar.setObjectName("statusbar")
        InCorrectAnswer.setStatusBar(self.statusbar)

        self.retranslateUi(InCorrectAnswer)
        QtCore.QMetaObject.connectSlotsByName(InCorrectAnswer)

    def retranslateUi(self, InCorrectAnswer):
        _translate = QtCore.QCoreApplication.translate
        InCorrectAnswer.setWindowTitle(_translate("InCorrectAnswer", "MainWindow"))
        self.label.setText(_translate("InCorrectAnswer", "<html><head/><body><p align=\"center\"><span style=\" font-size:22pt; font-weight:600; color:#aa0000;\">Неверно!</span></p></body></html>"))
        self.pushButton.setText(_translate("InCorrectAnswer", "Главное меню"))
        self.pushButton_2.setText(_translate("InCorrectAnswer", "Выбор задания"))
        self.pushButton_3.setText(_translate("InCorrectAnswer", "Вернутся к решению"))
        self.pushButton_4.setText(_translate("InCorrectAnswer", "Показать решение"))
