# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ResultOptionWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ResultOption(object):
    def setupUi(self, ResultOption):
        ResultOption.setObjectName("ResultOption")
        ResultOption.resize(290, 162)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        ResultOption.setFont(font)
        self.centralwidget = QtWidgets.QWidget(ResultOption)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(60, 90, 151, 31))
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 40, 141, 31))
        self.label.setObjectName("label")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(170, 40, 81, 31))
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        ResultOption.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ResultOption)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 290, 25))
        self.menubar.setObjectName("menubar")
        ResultOption.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ResultOption)
        self.statusbar.setObjectName("statusbar")
        ResultOption.setStatusBar(self.statusbar)

        self.retranslateUi(ResultOption)
        QtCore.QMetaObject.connectSlotsByName(ResultOption)

    def retranslateUi(self, ResultOption):
        _translate = QtCore.QCoreApplication.translate
        ResultOption.setWindowTitle(_translate("ResultOption", "MainWindow"))
        self.pushButton.setText(_translate("ResultOption", "Главное меню"))
        self.label.setText(_translate("ResultOption", "Количество баллов"))
