# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AddTask.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddTask(object):
    def setupUi(self, AddTask):
        AddTask.setObjectName("AddTask")
        AddTask.resize(795, 313)
        self.centralwidget = QtWidgets.QWidget(AddTask)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 100, 241, 61))
        self.label.setObjectName("label")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(280, 120, 181, 31))
        self.textEdit.setObjectName("textEdit")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, -10, 781, 121))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 180, 231, 21))
        self.label_3.setObjectName("label_3")
        self.textEdit_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_2.setGeometry(QtCore.QRect(280, 170, 181, 31))
        self.textEdit_2.setObjectName("textEdit_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(310, 220, 131, 41))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(580, 0, 211, 21))
        self.pushButton_2.setObjectName("pushButton_2")
        AddTask.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(AddTask)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 795, 21))
        self.menubar.setObjectName("menubar")
        AddTask.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(AddTask)
        self.statusbar.setObjectName("statusbar")
        AddTask.setStatusBar(self.statusbar)

        self.retranslateUi(AddTask)
        QtCore.QMetaObject.connectSlotsByName(AddTask)

    def retranslateUi(self, AddTask):
        _translate = QtCore.QCoreApplication.translate
        AddTask.setWindowTitle(_translate("AddTask", "MainWindow"))
        self.label.setText(_translate("AddTask", "Введите название файла без его расширения"))
        self.label_2.setText(_translate("AddTask", "<html><head/><body><p>Чтобы добавить новое задание вы должны добавть в папки Task и Res, соответственно, фото задания и решения. </p><p><span style=\" color:#ff0000;\">Важно</span> чтобы файлы имели ОДИНАКОВОЕ название иначе программа перестанет функционировать</p></body></html>"))
        self.label_3.setText(_translate("AddTask", "Введите ответ к этому заданию"))
        self.pushButton.setText(_translate("AddTask", "Записать"))
        self.pushButton_2.setText(_translate("AddTask", "Вернуться на предыдущую страницу"))
