# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AnswerWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Answer(object):
    def setupUi(self, Answer):
        Answer.setObjectName("Answer")
        Answer.resize(732, 617)
        self.centralwidget = QtWidgets.QWidget(Answer)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 10, 701, 431))
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 450, 51, 51))
        self.label_2.setObjectName("label_2")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(70, 460, 91, 31))
        self.textEdit.setObjectName("textEdit")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(30, 510, 141, 41))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(510, 460, 151, 41))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(510, 510, 151, 41))
        self.pushButton_3.setObjectName("pushButton_3")
        Answer.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Answer)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 732, 21))
        self.menubar.setObjectName("menubar")
        Answer.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Answer)
        self.statusbar.setObjectName("statusbar")
        Answer.setStatusBar(self.statusbar)

        self.retranslateUi(Answer)
        QtCore.QMetaObject.connectSlotsByName(Answer)

    def retranslateUi(self, Answer):
        _translate = QtCore.QCoreApplication.translate
        Answer.setWindowTitle(_translate("Answer", "MainWindow"))
        self.label_2.setText(_translate("Answer", "Ответ:"))
        self.pushButton.setText(_translate("Answer", "отправить на проверку"))
        self.pushButton_2.setText(_translate("Answer", "Показать решение"))
        self.pushButton_3.setText(_translate("Answer", "Вернуться к заданиям"))
