# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DecisionWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_decision(object):
    def setupUi(self, decision):
        decision.setObjectName("decision")
        decision.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(decision)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 771, 451))
        self.label.setText("")
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 500, 281, 41))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(500, 500, 281, 41))
        self.pushButton_2.setObjectName("pushButton_2")
        decision.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(decision)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        decision.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(decision)
        self.statusbar.setObjectName("statusbar")
        decision.setStatusBar(self.statusbar)

        self.retranslateUi(decision)
        QtCore.QMetaObject.connectSlotsByName(decision)

    def retranslateUi(self, decision):
        _translate = QtCore.QCoreApplication.translate
        decision.setWindowTitle(_translate("decision", "MainWindow"))
        self.pushButton.setText(_translate("decision", "Вернуться к выбору задач"))
        self.pushButton_2.setText(_translate("decision", "Вернуться в главное меню"))
