# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DelTaskWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DelTask(object):
    def setupUi(self, DelTask):
        DelTask.setObjectName("DelTask")
        DelTask.resize(848, 234)
        self.centralwidget = QtWidgets.QWidget(DelTask)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(130, 100, 291, 41))
        self.label.setObjectName("label")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(440, 110, 311, 31))
        self.textEdit.setObjectName("textEdit")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 30, 851, 61))
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(310, 150, 241, 41))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(640, 0, 211, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        DelTask.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(DelTask)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 848, 21))
        self.menubar.setObjectName("menubar")
        DelTask.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(DelTask)
        self.statusbar.setObjectName("statusbar")
        DelTask.setStatusBar(self.statusbar)

        self.retranslateUi(DelTask)
        QtCore.QMetaObject.connectSlotsByName(DelTask)

    def retranslateUi(self, DelTask):
        _translate = QtCore.QCoreApplication.translate
        DelTask.setWindowTitle(_translate("DelTask", "MainWindow"))
        self.label.setText(_translate("DelTask", "<html><head/><body><p><span style=\" font-size:10pt;\">Введите имя файла с заданием(без расширения)</span></p></body></html>"))
        self.label_2.setText(_translate("DelTask", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">Изменение файлов программы может привести к неработоспособности программы</span></p><p align=\"center\"><span style=\" font-size:14pt; color:#ff0000;\">Будте аккуратны</span></p></body></html>"))
        self.pushButton.setText(_translate("DelTask", "Удалить задание"))
        self.pushButton_2.setText(_translate("DelTask", "Вернуться на предыдущую страницу"))
