# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'InCorrectAnswerWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_InCorrectAnswer(object):
    def setupUi(self, InCorrectAnswer):
        InCorrectAnswer.setObjectName("InCorrectAnswer")
        InCorrectAnswer.resize(516, 145)
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        font.setBold(True)
        font.setWeight(75)
        InCorrectAnswer.setFont(font)
        self.centralwidget = QtWidgets.QWidget(InCorrectAnswer)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(170, 0, 151, 71))
        font = QtGui.QFont()
        font.setFamily("Caladea")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(0, 80, 101, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(130, 80, 101, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(250, 80, 121, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(390, 80, 111, 23))
        self.pushButton_4.setObjectName("pushButton_4")
        InCorrectAnswer.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(InCorrectAnswer)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 516, 17))
        self.menubar.setObjectName("menubar")
        InCorrectAnswer.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(InCorrectAnswer)
        self.statusbar.setObjectName("statusbar")
        InCorrectAnswer.setStatusBar(self.statusbar)

        self.retranslateUi(InCorrectAnswer)
        QtCore.QMetaObject.connectSlotsByName(InCorrectAnswer)

    def retranslateUi(self, InCorrectAnswer):
        _translate = QtCore.QCoreApplication.translate
        InCorrectAnswer.setWindowTitle(_translate("InCorrectAnswer", "MainWindow"))
        self.label.setText(_translate("InCorrectAnswer", "<html><head/><body><p><span style=\" font-size:22pt; font-weight:600; color:#aa0000;\">Неверно!</span></p></body></html>"))
        self.pushButton.setText(_translate("InCorrectAnswer", "Главное меню"))
        self.pushButton_2.setText(_translate("InCorrectAnswer", "Выбор задания"))
        self.pushButton_3.setText(_translate("InCorrectAnswer", "Вернутся к решению"))
        self.pushButton_4.setText(_translate("InCorrectAnswer", "Показать решение"))
