# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ResetStatisticsWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ResetStatistics(object):
    def setupUi(self, ResetStatistics):
        ResetStatistics.setObjectName("ResetStatistics")
        ResetStatistics.resize(487, 172)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        ResetStatistics.setFont(font)
        self.centralwidget = QtWidgets.QWidget(ResetStatistics)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 30, 491, 51))
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(140, 80, 221, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(230, 0, 261, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        ResetStatistics.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ResetStatistics)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 487, 25))
        self.menubar.setObjectName("menubar")
        ResetStatistics.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ResetStatistics)
        self.statusbar.setObjectName("statusbar")
        ResetStatistics.setStatusBar(self.statusbar)

        self.retranslateUi(ResetStatistics)
        QtCore.QMetaObject.connectSlotsByName(ResetStatistics)

    def retranslateUi(self, ResetStatistics):
        _translate = QtCore.QCoreApplication.translate
        ResetStatistics.setWindowTitle(_translate("ResetStatistics", "MainWindow"))
        self.label.setText(_translate("ResetStatistics", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Если вы нажмете на кнопку, то вся статистика сбросится</span></p></body></html>"))
        self.pushButton.setText(_translate("ResetStatistics", "Сброс"))
        self.pushButton_2.setText(_translate("ResetStatistics", "Вернуться на предыдущую страницу"))
