# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'StartOptionWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_StartOption(object):
    def setupUi(self, StartOption):
        StartOption.setObjectName("StartOption")
        StartOption.resize(356, 323)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        StartOption.setFont(font)
        self.centralwidget = QtWidgets.QWidget(StartOption)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(100, 90, 161, 41))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(100, 210, 161, 41))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 361, 91))
        self.label.setObjectName("label")
        StartOption.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(StartOption)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 356, 25))
        self.menubar.setObjectName("menubar")
        StartOption.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(StartOption)
        self.statusbar.setObjectName("statusbar")
        StartOption.setStatusBar(self.statusbar)

        self.retranslateUi(StartOption)
        QtCore.QMetaObject.connectSlotsByName(StartOption)

    def retranslateUi(self, StartOption):
        _translate = QtCore.QCoreApplication.translate
        StartOption.setWindowTitle(_translate("StartOption", "MainWindow"))
        self.pushButton.setText(_translate("StartOption", "Начать"))
        self.pushButton_2.setText(_translate("StartOption", "Главное меню"))
        self.label.setText(_translate("StartOption", "<html><head/><body><p align=\"center\">После нажатия на кнопку начать вам будет </p><p align=\"center\">предложено решить все 19 заданий,</p><p align=\"center\">после выведкутся ваши результаты</p></body></html>"))
